#!/usr/bin/python3

import os
import subprocess
from time import sleep

HOMEDIR = os.path.expanduser("~")
DIRECTORY = os.path.join(HOMEDIR, "Pictures/wallpaper/")

def ChangeWallpaper(wallpaper:str):

    out = subprocess.run(
            ['feh', '--no-fehbg', '--bg-center',
             '{}{}'.format(DIRECTORY, wallpaper)])

    if not(out.check_returncode()):
        sleep(300)

    else:
        return "Couldn't Set Wallpaper"

if __name__ == "__main__":

    while True:

        WALLPAPERS = os.listdir(path=DIRECTORY)
        for image in WALLPAPERS:
            ChangeWallpaper(image)

